### ISSUE TITLE
Question about test files

### ISSUE THREAD

**Issue by hwichan0720** [MLSP2024/MLSP_Data#1]
Hello,

I wanted to bring to your attention an observation regarding test data for the MLSP shared task.

While reviewing the current test files, we noticed discrepancies. Specifically, the example labeled "pt_579" is present in [multilex_test_all_combined_lcp_unlabelled.tsv](https://github.com/MLSP2024/MLSP_Data/blob/9df9eb670d77e8e584b6c3842cfb7f75aa6a7c3e/Data/Test/All/multilex_test_all_combined_lcp_unlabelled.tsv#L4414), but absent in [multilex_test_pt_lcp_unlabelled.tsv](https://github.com/MLSP2024/MLSP_Data/blob/main/Data/Test/Portuguese/multilex_test_pt_lcp_unlabelled.tsv).

We believe that the content of multilex_test_pt_lcp_unlabelled.tsv is accurate. This belief is grounded in the fact that the target token "pt_579" corresponds to "RT," which is a subword of "SCORTEN" and not a standalone word.

Could you please clarify which file is correct, and if necessary, make the appropriate revisions to the test files? 

Thank you for your attention to this issue.

**Comment by mattshardlow** [comment]
Thanks for bringing this to our attention. We made some edits to the Portuguese files because of tokens which were inconsistent. It may be the case that the edits have not been reflected in both files. We will try and resolve this quickly.

@KaiNorth - please can you take a look.

**Comment by KaiNorth** [comment]
Thank you for reporting the issue. We have now updated the Portuguese instances in the ALL directory so that they reflect the instances in the language specific directory. You will find that RT is no longer included. 

Please reach out if you have any other issues!
